# experiment config
exp_name: local-debug

train: True
resume: False


pol_type: agent_pol #shared_pol shared policy or each agent will have its own policy
# pol_type: shared_pol



algorithm:
  # name: PPO
  name: CentralizedCritic
  config: 'ppo_config.yaml'
environment_cls: 'FlexEnv'

#tune config
mode: max
metric: episode_reward_mean

# Run config
verbose: 0

#trainable config
n_iters: 11
checkpoint_freq: 5

#resources
num_cpu_1: 1.0
num_cpu_2: 1.0
num_gpu: 0.0
cpu_factor: 6

spill_dir: /home/omega/Documents/FCUL/Projects/FlexEnvMas/raylog/spill1
