#Config file for scenarios definitions
#game_setup: 'cooperative_colective'
#game_setup: 'cooperative_colective_boost'
#game_setup: 'cooperative_colective_sigma'
game_setup: 'cooperative_colective_scaled_sigma'
#game_setup='cooperative'
#game_setup='competitive'
# reward_func: 'tar_sigma_reward'
reward_func: 'simple_reward'
# reward_func: 'simple_reward_v2'
# reward_func: 'weight_reward'
# reward_func: 'comp_weight_reward'
# reward_func: 'weight_reward_var_w'
# reward_func: reward_unique
reward_params:
  g: 0.2
  penal: -5.0
  #g: 1
  # a: -1.65
  # b: -3.2
  # c: 100
  # d: -0.01
  #a: -0.4
  #b: -3.2
  #c: 100
  #d: -0.01
