tstep:
  max: 100000
  min: -1.0
  use: true
minutes:
  max: 1440
  min: -1.0
  use: true
sin:
  max: 1.0
  min: -1.0
  use: true
PV_sum:
  max: 100
  min: 0
  use: true
load:
  max: 100
  min: -1.0
  use: true
gen:
  max: 100
  min: -1.0
  use: true
