minutes:
  max: 1440
  min: -1.0
  use: True
sin:
  max: 1.0
  min: -1.0
  use: True
cos:
  max: 1.0
  min: -1.0
  use: True
load0:
  max: 100
  min: -1.0
  use: True
gen0:
  max: 100
  min: -1.0
  use: True
excess0:
  max: 100
  min: -1.0
  use: True
tar_buy:
  max: 1.0
  min: -1.0
  use: True
E_prof_rem:
  max: 100.0
  min: -1.0
  use: True
y_s:
  max: 20
  min: -1.0
  use: True
pv_sum:
  max: 1000
  min: -1.0
  use: True
tar1:
  max: 100
  min: -1.0
  use: True
tar2:
  max: 100
  min: -1.0
  use: True
tar3:
  max: 100
  min: -1.0
  use: False
tar4:
  max: 100
  min: -1.0
  use: False
tar5:
  max: 100
  min: -1.0
  use: False
tar6:
  max: 100
  min: -1.0
  use: False
tar7:
  max: 1.0
  min: -1.0
  use: False
tar8:
  max: 1.0
  min: -1.0
  use: False
tar9:
  max: 100
  min: -1.0
  use: False
tar10:
  max: 100
  min: -1.0
  use: False
tar11:
  max: 100
  min: -1.0
  use: False
tar12:
  max: 100
  min: -1.0
  use: False
tar13:
  max: 100
  min: -1.0
  use: False
tar14:
  max: 100
  min: -1.0
  use: False
tar15:
  max: 1.0
  min: -1.0
  use: False
tar16:
  max: 1.0
  min: -1.0
  use: False
tar17:
  max: 100
  min: -1.0
  use: False
tar18:
  max: 100
  min: -1.0
  use: False
tar19:
  max: 100
  min: -1.0
  use: False
tar20:
  max: 100
  min: -1.0
  use: False
tar21:
  max: 100
  min: -1.0
  use: False
tar22:
  max: 100
  min: -1.0
  use: False
tar23:
  max: 1.0
  min: -1.0
  use: False
tar24:
  max: 1.0
  min: -1.0
  use: False
tar_d:
  max: 1.0
  min: -1.0
  use: True
tar_mean:
  max: 1.0
  min: -1.0
  use: True
tar_stdev:
  max: 1.0
  min: -1.0
  use: True
tar_var:
  max: 1.0
  min: -1.0
  use: True
