minutes:
  max: 1440
  min: -1.0
  use: true
sin:
  max: 1.0
  min: -1.0
  use: true
cos:
  max: 1.0
  min: -1.0
  use: true
load0:
  max: 100
  min: -1.0
  use: true
gen0:
  max: 100
  min: -1.0
  use: true
excess0:
  max: 100
  min: -1.0
  use: true
tar_buy:
  max: 1.0
  min: -1.0
  use: true
E_prof_rem:
  max: 100.0
  min: -1.0
  use: true
y_s:
  max: 20
  min: -1.0
  use: true
pv_sum:
  max: 1000
  min: -1.0
  use: true
tar1:
  max: 100
  min: -1.0
  use: true
tar2:
  max: 100
  min: -1.0
  use: true
tar3:
  max: 100
  min: -1.0
  use: true
tar4:
  max: 100
  min: -1.0
  use: true
tar5:
  max: 100
  min: -1.0
  use: true
tar6:
  max: 100
  min: -1.0
  use: true
tar7:
  max: 1.0
  min: -1.0
  use: true
tar8:
  max: 1.0
  min: -1.0
  use: true
tar_d:
  max: 1.0
  min: -1.0
  use: True
