#exp_name
#exp_name: exp0
# exp_name: exp01
# exp_name: exp21
# exp_name: exp2
# exp_name: fcul1-3ag-IL
# exp_name: fcul1
exp_name: local-debug
# exp_name: exp21
# exp_name: fc1-2Ag
#exp_name: fc1-2Ag-1Day
# exp_name: fcul1-3ag-CC-newobs
# exp_name: fcul1-3ag-IL-newobs
#exp_name: fcul1-3ag-IL-newnet
# exp_name: fcul1-3ag-IL-oldnet
# exp_name: fcul1-3ag-CC-oldnet
#exp_name: fcul1-3ag-IL-1day
