# Battery configuration file
# Units are explicitly indicated
# All SoC values are in fraction [0-1] (if using capacity explicitly, SoC is in kWh and Capacity must be included)

bat1:
  Capacity: 10               # Battery nominal capacity [kWh]
  SoC_min: 0.1               # Minimum allowed SoC as fraction of Capacity [0-1] (e.g., 0.1 for 10%)
  SoC_max: 1.0               # Maximum allowed SoC as fraction of Capacity [0-1] (1.0 means 100%)
  P_charge_max: 2            # Maximum charge power [kW]
  P_discharge_max: 2         # Maximum discharge power [kW]
  eta_c: 0.95                # Charging efficiency [-] (e.g., 0.95 means 95%)
  eta_d: 0.95                # Discharging efficiency [-]
  SoC_init: 0.5              # Initial SoC as fraction of Capacity [0-1] (e.g., 0.5 for 50%)
  
bat2:
  Capacity: 20               # Battery nominal capacity [kWh]
  SoC_min: 0.1               # Minimum allowed SoC fraction [0-1]
  SoC_max: 1.0               # Maximum allowed SoC fraction [0-1]
  P_charge_max: 3            # Maximum charge power [kW]
  P_discharge_max: 3         # Maximum discharge power [kW]
  eta_c: 0.90                # Charging efficiency [-]
  eta_d: 0.92                # Discharging efficiency [-]
  SoC_init: 0.5              # Initial SoC fraction [0-1]
